name: Build Backend and Frontend

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # ──────────────────────────────────────
      # Backend (NestJS)
      # ──────────────────────────────────────

      - name: Install backend dependencies
        working-directory: ./server
        run: npm ci

      - name: Build backend
        working-directory: ./server
        run: npm run build

      - name: Upload backend dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: |
            server/dist/
            server/package.json
            server/package-lock.json

      # ──────────────────────────────────────
      # Frontend (Vite)
      # ──────────────────────────────────────

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm ci

      - name: Build frontend
        working-directory: ./client
        run: npm run build

      - name: Upload frontend dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: |
            client/dist/
            client/package.json
            client/package-lock.json
